### ISSUE TITLE
wxss.test.js测试失败，那内容不匹配，但是查看不同只有换行符不一致

### ISSUE THREAD

**Issue by XingtianXin** [wechat-miniprogram/miniprogram-simulate#16]
Windows下git直接获取项目，用webstorm打开项目后，install依赖。然后跑all test.
只有一条case不对
`  Error: expect(received).toBe(expected) // Object.is equality

  at Object.toBe (D:\GitWS\miniprogram-simulate\test\unit\wxss.test.js:6:72)

    at Object.asyncJestTest (D:\GitWS\miniprogram-simulate\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)

    at resolve (D:\GitWS\miniprogram-simulate\node_modules\jest-jasmine2\build\queue_runner.js:56:12)

    at new Promise (<anonymous>)

    at mapper (D:\GitWS\miniprogram-simulate\node_modules\jest-jasmine2\build\queue_runner.js:43:19)

    at promise.then (D:\GitWS\miniprogram-simulate\node_modules\jest-jasmine2\build\queue_runner.js:87:41)

    at processTicksAndRejections (internal/process/next_tick.js:81:5)`
点击查看不同，Click to see the differences

在Comparison Failure页面显示：
Contents have differences only in line separators.
Excepted 是LF, Actual是CRLF

尝试：
修改了Webstorm里的settings->editor->code style->line separators 为Unix and OS X(\n)
仍然有错误。

重新编辑了所有对比部门的换行，还是有错误。

请问：
有谁遇到类似的问题么？是如何解决的？

**Comment by XingtianXin** [comment]
是Git工具的问题
Windows上把git的自动转换换行符设置为false，重新获取一下code就好了

git config --global core.autocrlf false
