### ISSUE TITLE
编译 .wxml 文件错误：index.wxml:1:1:../../wxs/index.wxs not found from index.wxml

### ISSUE THREAD

**Issue by leo4developer** [wechat-miniprogram/miniprogram-simulate#48]
如题，单元测试时，组件的wxml文件中引用了wxs文件，报错
`编译 .wxml 文件错误：index.wxml:1:1:../../wxs/index.wxs not found from index.wxml

       5 |   // 此处必须使用这种拼接的写法，否则会找不到文件路径
       6 |   // 必须使用dist文件夹下的组件，使用src文件夹下面的代码不会加载样式文件
    >  7 |   const id = simulate.load(path.join(__dirname, '../../dist/components/coupon-wx/index'));
         |                       ^
       8 |   const comp = simulate.render(id); // 渲染成自定义组件树实例
       9 | 
      10 |   const parent = document.createElement('parent-wrapper'); // 创建父亲节点

      at wxmlToJS (node_modules/miniprogram-compiler/src/wcc.js:110:11)
      at Object.wxmlToJs (node_modules/miniprogram-compiler/src/index.js:24:27)
      at Object.getWxml (node_modules/miniprogram-simulate/src/compile.js:29:52)
      at register (node_modules/miniprogram-simulate/src/index.js:98:30)
      at Object.load (node_modules/miniprogram-simulate/src/index.js:141:16)
      at Object.<anonymous> (test/components/coupon-wx.test.js:7:23)`

**Comment by leo4developer** [comment]
![component](https://user-images.githubusercontent.com/15160478/73993917-a3c4f880-498e-11ea-95c4-b6e74fbc6607.jpg)
wxs的外链引用

**Comment by chenzhutian** [comment]
所以解决方案是啥? 把相对引用改成绝对引用?
我应了一个第三方的包, 里面用了相对应用, 要手动去改太蛋疼了
