### ISSUE TITLE
如何测试 `pageLifeTimes` 中的组件逻辑

### ISSUE THREAD

**Issue by Ayase-252** [wechat-miniprogram/miniprogram-simulate#73]
请问一下当组件有部分逻辑在 `pageLifetime` 中的生命周期时，组件如何测试？ 调用 `comp.triggerLifeTime("show")` 失败

复现 repo: https://github.com/Ayase-252/wx-page-life-time-issue

复现步骤：
1. clone repo
2. `yarn`
3. `yarn test`

期望：
测试通过

现状：
```
➜  page-life-time git:(master) ✗ yarn test
yarn run v1.21.1
$ jest
 FAIL  demo/__tests__/index.spec.js
  demo
    ✕ should equal 1 (192 ms)

  ● demo › should equal 1

    TypeError: Cannot read property 'call' of undefined

      16 |     const container = document.createElement("div")
      17 |     await simulate.sleep(10)
    > 18 |     renderedComp.triggerLifeTime("show")
         |                  ^
      19 |     expect(renderedComp.querySelector("#text").dom.textContent).toBe("1")
      20 |   })
      21 | })

      at g.triggerLifeTime (node_modules/miniprogram-exparser/exparser.min.js:3:14694)
      at RootComponent.triggerLifeTime (node_modules/j-component/src/render/component.js:218:24)
      at Object.<anonymous> (demo/__tests__/index.spec.js:18:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.594 s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by JuneAndGreen** [comment]
miniprogram-simulate@1.3.2 支持接口 triggerPageLifeTime，用来触发页面的生命周期。
