### ISSUE TITLE
Feat request: 抽象节点支持

### ISSUE THREAD

**Issue by justan** [wechat-miniprogram/miniprogram-simulate#78]
当前自定义组件 `virtualHost: true` 的时候会报错：
```
TypeError: Cannot read property 'addEventListener' of undefined

      30 |     pt.join(__dirname, '../mp/components/container/index')
      31 |   );
    > 32 |   const comp = simulate.render(id, {});
         |                         ^
      33 |

      at RootComponent._bindEvent (node_modules/j-component/src/render/component.js:293:9)
      at new RootComponent (node_modules/j-component/src/render/component.js:279:10)
      at Object.create (node_modules/j-component/src/index.js:41:12)
      at Object.render (node_modules/miniprogram-simulate/src/index.js:197:23)
      at Object.<anonymous> (src/test/Container.test.js:32:25)
```

所以完全没办法测试虚拟节点的自定义组件，请教支持的计划。

**Comment by JuneAndGreen** [comment]
virtual host 应该很早之前就支持了，你确定是因为加了这个配置就报错么？

**Comment by JuneAndGreen** [comment]
其实之前已支持，只是之前只支持到子级组件，没有支持到根组件上，现在已补充：

更新至：miniprogram-simulate@1.4.1 及其依赖  j-component@1.4.3
