### ISSUE TITLE
spawnSync ENOENT

### ISSUE THREAD

**Issue by perowong** [wechat-miniprogram/miniprogram-simulate#99]
```js
import simulate from 'miniprogram-simulate';
import path from 'path';

test('Test loadmore', () => {
  const id = simulate.load(path.join(__dirname, '../loadmore/loadmore'));
  const comp = simulate.render(id);

  const parent = document.createElement('loadmore-wrapper');
  comp.attach(parent);

  expect(comp.dom.innerHTML.includes('加载更多')).toBe(false);
  expect(comp.dom.innerHTML.includes('正在加载')).toBe(false);

  comp.detach();
});
```
上面这段测试用例在mac上跑是正常的，但是push到gitlab上通过pipeline跑的时候报如下错误

```
✕ Test loadmore (35 ms)

  ● Test loadmore

    spawnSync /builds/proj/node_modules/miniprogram-compiler/bin/linux/wcc ENOENT

      3 |
      4 | test('Test loadmore', () => {
    > 5 |   const id = simulate.load(path.join(__dirname, '../loadmore/loadmore'));
        |                       ^
      6 |   const comp = simulate.render(id);
      7 |
      8 |   const parent = document.createElement('loadmore-wrapper');

      at wxmlToJS (node_modules/miniprogram-compiler/src/wcc.js:105:15)
      at Object.wxmlToJs (node_modules/miniprogram-compiler/src/index.js:23:27)
      at Object.getWxml (node_modules/miniprogram-simulate/src/compile.js:29:52)
      at register (node_modules/miniprogram-simulate/src/index.js:124:30)
      at Object.load (node_modules/miniprogram-simulate/src/index.js:166:16)
      at Object.<anonymous> (miniprogram/components/__tests__/loadmore.spec.js:5:23)

Summary of all failing tests
FAIL miniprogram/components/__tests__/loadmore.spec.js
```

看了源码是这段里的spawnSync那行报错了
```js
function wxmlToJS(rootPath, files, wxsFiles, { cut, maxBuffer } = {}) {
  const type = cut ? '-xc' : '-cc'
  files = getAllFiles(rootPath, files)

  // @TODO，如果遇到参数过长被操作系统干掉的情况，可以使用 --config-path FILE 配置，参数空格换成空行
  const componentArgs = getComponentArgs(files)
  const args = ['-d', type, componentArgs.join(' ')]
    .concat(files.map(file => file.pagePath))
    .concat(wxsFiles)
    .concat(['-gn', '$gwx'])

  const wxmlParserPath = getWXMLParsePath()
  const wcc = spawnSync(wxmlParserPath, args, {
    cwd: rootPath,
    maxBuffer: maxBuffer || 1024 * 1024,
  })

  if (wcc.status === 0) {
    return wcc.stdout.toString()
  } else if (wcc.error) {
    throw wcc.error
  } else {
    throw new Error(`编译 .wxml 文件错误：${wcc.stderr.toString()}`) 
  }
}
```

对应`wxmlParserPath`的定义在Linux上是path.join(__dirname, '../bin/linux/wcc')
```js
const fileName = process.platform === 'darwin' ? '../bin/mac/wcc' : process.platform === 'linux' ? '../bin/linux/wcc' : '../bin/windows/wcc.exe'
  wxmlParserPath = path.join(__dirname, fileName)
```

随后在gitlab-runner的pipeline里看了下有没有这个文件，是有的：
```
m$ ls /builds/proj/node_modules/miniprogram-compiler/bin/linux/
wcc
wcsc
```

不知这里为啥在gitlab-runner上就报错了😂？ @JuneAndGreen

**Comment by JuneAndGreen** [comment]
我本地看是正常的，会不会没有权限？

**Comment by perowong** [comment]
> 我本地看是正常的，会不会没有权限？

```js
 // 尝试修改权限
  try {
    fs.chmodSync(wxmlParserPath, 0o777)
  } catch (err) {
    // ignore
  }

  return wxmlParserPath
```
我看有源码里有修改权限，我看看把err throw出来，是不是这里出问题了

**Comment by perowong** [comment]
> 我本地看是正常的，会不会没有权限？

通过bash修改权限后，pipeline里的日志我看是正常的，但是执行到spawnSync(wxmlParserPath 这里还是报同样的错

![WX20221125-132029@2x](https://user-images.githubusercontent.com/44636561/203906674-e36c7135-e1d4-40c8-a2f5-5e955037d510.png)

**Comment by perowong** [comment]
问题解决了，是dock容器底层库导致的，alpine镜像使用的是musl libc而不是gnu libc😂
